<?php

/*
 * @FILES add files consorme.
 */

/**
 * 
 */
function contact_us_menu() {
    
}

function contact_us_form($form, &$form_state) {
    // Markup de gestion des message d'erreur ou de succes.
    $form['box'] = array(
        '#type' => 'markup',
        '#prefix' => '<div id="box-message">',
        '#suffix' => '</div>',
        '#markup' => ' ',
    );
    
    $form['boxing_interne']['prenom'] = array(
        '#type' => 'textfield',
        '#title' => t('Prénom'),  
        '#size' => 30,
        '#prefix' => '<div class="box-contact-interne">',
    );
    $form['boxing_interne']['nom'] = array(
        '#type' => 'textfield',
        '#title' => t('Nom'),
        '#size' => 30,
    );
    $form['boxing_interne']['objet'] = array(
        '#type' => 'textfield',
        '#title' => t('Objet'),
        '#size' => 30,
    );
    $form['boxing_interne']['email'] = array(
        '#type' => 'textfield',
        '#title' => t('E-mail'),
        '#size' => 30,
        '#suffix' => '</div>',
    );
    $form['boxing_interne']['message'] = array(
        '#type' => 'textarea',
        '#title' => t('Message'),
        '#cols' => 30,
    );

    $form ['submit'] = array(
        '#type' => 'submit',
        '#ajax' => array(
            'callback' => 'contact_us_form_callback_message',
            'wrapper' => 'box',
        ),
        '#value' => t('Envoyer '),
    );

    return $form;
    
    
}

function contact_us_form_validate($form, &$form_state) {
    
}


function contact_us_form_submit($form, &$form_state) {
    
}

function contact_us_form_callback_message($form, &$form_state) {
    
}